on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'testdata'
      - 'sample'
      - 'scan/testdata'
      - 'convert/testdata'
      - 'process/testdata'
      - '**.go'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'testdata'
      - 'sample'
      - 'scan/testdata'
      - 'convert/testdata'
      - 'process/testdata'
      - '**.go'
  workflow_dispatch:
name: test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x, 1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Run tests
      run: |
        go mod tidy
        go test -v ./...
